apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-blue
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: "blue"
    spec:
      containers:
      - name: nginxpod
        image: nginx:1.18
        ports:
        - containerPort: 80