apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  volumes:
  - name: html
    emptyDir: {}
  containers:
  - name: datagenerator
    image: debian
    volumeMounts:
    - name: html
      mountPath: /html
    command: ["/bin/sh", "-c"]
    args:
      - while true; do
          date >> /html/index.html;
          sleep 10;
        done
  - name: datadisplayer
    image: nginx
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html