apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: testcronjob
spec:
  schedule: "*/2 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: testjob
            image: bash
            command: ["echo", "kubernetes training"]
          restartPolicy: OnFailure