apiVersion: v1
kind: Pod
metadata:
  name: configmappod
spec:
  containers:
    - name: configmappod
      image: nginx
      envFrom:
        - configMapRef:
            name: exampleconfigmap